blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostDeleteView, PostUpdateView

from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('/posts', PostListView.as_view(), name='posts'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('create', PostCreateView.as_view(), name='post_create'),
    path('update/<int:pk>', PostUpdateView.as_view(), name='post_update'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls',namespace='mailings')),
    path('', include('users.urls',namespace='users')),
    path('', include('blog.urls',namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.apps import MailingsConfig
from mailings.views import NotificationListView, NotificationDetailView, NotificationCreateView, \
    NotificationDeleteView, MessageListView, MessageDetailView, MessageCreateView, MessageDeleteView, ClientListView, \
    ClientDeleteView, ClientUpdateView, ClientCreateView, ClientDetailView, MessageUpdateView, NotificationUpdateView, \
    finish_notification, IndexView, AttemptListView

app_name = MailingsConfig.name



urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('notifications', NotificationListView.as_view(), name='notifications'),
    path('notification/<int:pk>', NotificationDetailView.as_view(), name='notification_detail'),
    path('notification/create', NotificationCreateView.as_view(), name='notification_create'),
    path('notification/delete/<int:pk>', NotificationDeleteView.as_view(), name='notification_delete'),
    path('notification/update/<int:pk>', NotificationUpdateView.as_view(), name='notification_update'),
    path('notification/finish/<int:pk>', finish_notification, name='notification_finish'),
    path('messages', MessageListView.as_view(), name='messages'),
    path('message/<int:pk>', MessageDetailView.as_view(), name='message_detail'),
    path('message/create', MessageCreateView.as_view(), name='message_create'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('message/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('clients', ClientListView.as_view(), name='clients'),
    path('client/create', ClientCreateView.as_view(), name='client_create'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('client/update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('notification-attempt', AttemptListView.as_view(), name='attempts'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, recover_password, UsersListView, block_user, unblock_user

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('recover_password/', recover_password, name='recover_password'),
    path('/', UsersListView.as_view(), name='users'),
    path('/block/<int:pk>', block_user, name='block_user'),
    path('/unblock/<int:pk>', unblock_user, name='block_user'),
]

mailings/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}
PERIOD = [('w', 'Раз в неделю'), ('d', 'Раз в день'), ('m', 'Раз в месяц')]
STATUS_ = [('f', 'Завершена'), ('c', 'Создана'), ('p', 'Запущена')]
# Create your models here.

class Client(models.Model):
    email = models.EmailField(verbose_name='контактный email')
    name = models.CharField(max_length=255, verbose_name='фио')
    comments = models.TextField(**NULLABLE, verbose_name='комментарий')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='чей клиент')

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'

    def __str__(self):
        return f'{self.name} - {self.email}'

class Message(models.Model):
    title = models.CharField(max_length=255, verbose_name='тема письма')
    body = models.TextField(verbose_name='тело письма')

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сooбщения'

    def __str__(self):
        return self.title

class Notification(models.Model):
    start_at = models.DateTimeField(verbose_name='дата начала отправки рассылки')
    finish_at = models.DateTimeField(verbose_name='дата окончания отправки рассылки')
    first_send_time = models.DateTimeField(verbose_name='дата и время первой отправки рассылки', **NULLABLE)
    period = models.CharField(max_length=1, choices=PERIOD, verbose_name='периодичность')
    status = models.CharField(default= 'c', max_length=1, choices=STATUS_, verbose_name='статус рассылки')
    client = models.ManyToManyField(Client, verbose_name='клиент', related_name='clients')
    creator = models.ForeignKey(User, verbose_name='автор', related_name='users', default=1, on_delete=models.CASCADE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение')
    last_send_time = models.DateTimeField(verbose_name='дата и время последней отправки рассылки', **NULLABLE)

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        permissions = [
            ('update_status', 'Может отключать рассылки'),
        ]

    def __str__(self):
        return f'{self.message}'

class NotificationAttempt(models.Model):
    last_attempt_at = models.DateTimeField(auto_now_add=True, verbose_name='время последней попытки')
    is_sent = models.BooleanField(default=False, verbose_name='статус попытки')
    server_message = models.TextField(**NULLABLE, verbose_name='ответ почтового сервера')
    notification = models.ForeignKey(Notification, on_delete=models.CASCADE, verbose_name='рассылка')

    class Meta:
        verbose_name = 'попытка рассылки'
        verbose_name_plural = 'попытки рассылки'

    def __str__(self):
        return f'{self.pk} - {self.is_sent}'

mailings/forms.py
from django import forms
from mailings.models import Notification


class FormStylesMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field.widget.__class__.__name__ == 'CheckboxInput':
                field.widget.attrs['class'] = 'form-check-input'
            elif field.widget.__class__.__name__ != 'DateTimeInput':
                field.widget.attrs['class'] = 'form-control'

class NotificationForm(FormStylesMixin, forms.ModelForm):
    class Meta:
        model = Notification
        fields = ('start_at', 'finish_at', 'period','client', 'message')

        widgets = {
            'start_at': forms.SelectDateWidget,
            'finish_at': forms.SelectDateWidget,
        }

        css = {
            'all': ('css/styles.css',)
        }
        js = ('js/script.js',)

mailings/views.py
from tempfile import template

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template.defaulttags import comment
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DeleteView, DetailView, CreateView, UpdateView, TemplateView

from blog.models import Post
from mailings.forms import NotificationForm
from mailings.models import Notification, Message, Client, NotificationAttempt
from blog.services import get_cached_posts
from mailings.services import get_cached_mailing_count, get_cached_active_mailings, get_cached_users_count


# Create your views here.
class IndexView(TemplateView):
    template_name = 'mailings/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mailing_count'] = get_cached_mailing_count()
        context['active_mailings'] = get_cached_active_mailings()
        context['users_count'] = get_cached_users_count()
        context['posts'] = get_cached_posts()[:3]
        return context




class NotificationListView(LoginRequiredMixin, ListView):
    model = Notification

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(creator=self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        context_data['period'] = {'w': 'Раз в неделю', 'd': 'Раз в день', 'm': 'Раз в месяц'}
        context_data['status'] = {'f':'Завершена', 'c': 'Создана', 'p': 'Запущена'}
        return context_data

class NotificationDetailView(DetailView):
    model = Notification


class NotificationCreateView(LoginRequiredMixin, CreateView):
    model = Notification
    form_class = NotificationForm
    success_url = reverse_lazy('mailings:notifications')

    def form_valid(self, form):
        fields = form.save(commit=False)
        fields.creator = self.request.user
        fields.save()
        return super().form_valid(form)

class NotificationUpdateView(LoginRequiredMixin, UpdateView):
    model = Notification
    form_class = NotificationForm

    def get_success_url(self):
        return reverse('mailings:notification_detail', args=[self.kwargs.get('pk')])

class NotificationDeleteView(LoginRequiredMixin, DeleteView):
    model = Notification
    success_url = reverse_lazy('mailings:notifications')

def finish_notification(request, pk):
    notification = Notification.objects.get(pk=pk)
    notification.status = 'f'
    notification.save()
    return redirect(request.META.get('HTTP_REFERER'))

class MessageListView(LoginRequiredMixin, ListView):
    model = Message

class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message

class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    fields = ('title', 'body',)

    def get_success_url(self):
        return reverse('mailings:message_detail', args=[self.kwargs.get('pk')])

class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ('title', 'body')
    success_url = reverse_lazy('mailings:messages')

class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailings:messages')


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(owner=self.request.user)
        return qs


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('name', 'email', 'comments',)
    success_url = reverse_lazy('mailings:clients')

    def form_valid(self, form):
        fields = form.save(commit=False)
        fields.owner = self.request.user
        fields.save()
        return super().form_valid(form)

class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    fields = ('name', 'email', 'comments',)

    def get_success_url(self):
        return reverse('mailings:client_detail', args=[self.kwargs.get('pk')])

class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailings:clients')

class AttemptListView(LoginRequiredMixin, ListView):
    model = NotificationAttempt

mailings/templates/mailings/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Рассылки</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        {% load static %}
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
       {% include './header.html'%}
       <div class="row gx-12 gx-lg-5 align-items-center my-5">
           <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'img/1.png'%}" alt="..." /></div>
       </div>
       {% block content %}
       {% endblock content %}
       {% include './footer.html'%}
       <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
       <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

mailings/templates/mailings/client_confirm_delete.html
{% extends './base.html'%}
{% load static %}
{% block content %}
    <div class="container">
      <form method="post">
        {% csrf_token %}
        <p>Удалить пользователя: {{ object.name }}?</p>
        <button type="submit" class="btn btn-danger">Подтвердить удаление</button>
        <a class="btn btn-warning" href="{% url 'mailings:clients' %}">Отменить удаление</a>
      </form>
    </div>
{% endblock %}

mailings/templates/mailings/client_detail.html
{% extends './base.html'%}
{% load static %}
{% block content %}
  <div class="container px-4 px-lg-5">
        {% if object %}
            <div class="col-md-12 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">{{ object.name}}</h2>
                        <p class="card-text">{{ object.email }}</p>
                        <p class="card-text">{{ object.comments}}</p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-danger btn-sm" href="{% url 'mailings:client_delete' object.pk %}">Удалить</a>
                        <a class="btn btn-info btn-sm mb-10" href="{% url 'mailings:client_update' object.pk %}">Изменить</a>
                    </div>

                </div>
            </div>
        {% else %}
            <h2 class="card-title">Нет такого клиента</h2>
        {% endif %}
        </div>
{% endblock content %}

mailings/templates/mailings/footer.html
<footer class="py-5 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Сервис рассылок {% now "Y" %}</p></div>
</footer>

mailings/templates/mailings/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="/">Сервис рассылок</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Домой</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'mailings:clients' %}">Клиенты</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'mailings:messages' %}">Сообщения</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'mailings:notifications' %}">Рассылки</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'blog:posts' %}">Блог</a></li>
                        {% if perms.users.view_clients_list %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'users:users' %}">Пользователи</a></li>
                        {% endif %}
                        {% if not user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'users:login'%}">Войти</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'users:register'%}">Зарегистрироваться</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'users:recover_password'%}">Восстановить пароль</a></li>
                        {% else %}
                            <li class="nav-item">
                                <form style="display: inline" method="post" action="{% url 'users:logout' %}">
                                    {% csrf_token %}
                                    <button style="background-color: inherit; border: none" class="nav-link" type="submit">Выйти</button>
                                </form>
                            </li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'mailings:attempts'%}">Попытки</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'users:profile'%}">Профиль</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
</nav>

mailings/templates/mailings/index.html
{% extends './base.html'%}
{% load static %}
{% block content %}
<div class="card text-white bg-secondary my-5 py-4 text-center">
       <div class="card-body">
           <p class="text-white m-0">
               В сервисе создано рассылок - {{ mailing_count }}
           </p>
           <p class="text-white m-0">
               Из них активных -  {{ active_mailings }}
           </p>
           <p class="text-white m-0">
               Пользователей - {{ users_count }}
           </p>
       </div>
</div>
{% for post in posts %}
      <div class="card mb-5">
          <div class="col-md-4 mb-5">
              <img src="../media/{{ post.preview }}" class="card-img-top"  alt="...">
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ post.title }} </h5>
            <p class="card-text">{{ post.content }}</p>
            <a href="{% url 'blog:post_detail' post.pk %}" class="btn btn-primary">Просмотреть пост</a>
          </div>
      </div>
{% endfor %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5">
        <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Список клиентов</h2>
                            <p class="card-text">Чтобы получить список клиентов нажмите кнопку ниже</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="{% url 'mailings:clients' %}">Просмотреть клиентов</a></div>
                    </div>
                </div>
        <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Список сообщений</h2>
                            <p class="card-text">Чтобы получить список сообщений нажмите кнопку ниже</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="{% url 'mailings:messages' %}">Просмотр сообщений</a></div>
                    </div>
                </div>
        <div class="col-md-4 mb-5">
        <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Список рассылок</h2>
                            <p class="card-text">Чтобы получить список зассылок нажмите кнопку ниже</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="{% url 'mailings:notifications' %}">Просмотр рассылок</a></div>
                    </div>
        </div>
    </div>
</div>
{% endblock content %}

mailings/templates/mailings/message_confirm_delete.html
{% extends './base.html'%}
{% load static %}
{% block content %}
    <div class="container">
      <form method="post">
        {% csrf_token %}
        <p>Удалить сообщение: {{ object.title }}?</p>
        <button type="submit" class="btn btn-danger">Подтвердить удаление</button>
        <a class="btn btn-warning" href="{% url 'mailings:messages' %}">Отменить удаление</a>
      </form>
    </div>
{% endblock %}

mailings/templates/mailings/message_detail.html
{% extends './base.html'%}
{% load static %}
{% block content %}
  <div class="container px-4 px-lg-5">
        {% if object %}
            <div class="col-md-12 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">{{ object.title}}</h2>
                        <p class="card-text">{{ object.body }}</p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-danger btn-sm" href="{% url 'mailings:message_delete' object.pk %}">Удалить</a>
                        <a class="btn btn-info btn-sm mb-10" href="{% url 'mailings:message_update' object.pk %}">Изменить</a>
                    </div>

                </div>
            </div>
        {% else %}
            <h2 class="card-title">Нет такого сообщения</h2>
        {% endif %}
        </div>
{% endblock content %}

mailings/templates/mailings/message_list.html
{% extends './base.html'%}
{% load static %}
{% block content %}
  <div class="container px-4 px-lg-5">
            <!-- Heading Row-->
            {% if object_list %}
            {% for message in object_list %}
                <div class="row gx-12 gx-lg-5">
                    <div class="col-md-12 mb-5">
                        <div class="card h-100">
                            <div class="card-body">
                                <h2 class="card-title">{{ message.title }}</h2>
                                <p class="card-text">{{ message.body }}</p>
                            </div>
                            <div class="card-footer">
                                <a class="btn btn-primary btn-sm" href="{% url 'mailings:message_detail' message.pk %}">Показать сообщение</a>
                                <a class="btn btn-info btn-sm mb-10" href="{% url 'mailings:message_create' %}">Создать новое сообщение</a>
                                {% if perms.mailings.update_message %}
                                    <a class="btn btn-warning btn-sm mb-10" href="{% url 'mailings:message_update' message.pk %}">Изменить сообщение</a>
                                {% endif %}
                                {% if perms.mailings.update_message %}
                                    <a class="btn btn-danger btn-sm mb-10" href="{% url 'mailings:message_delete' message.pk %}">Удалить сообщение</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

            {% else %}
                <h2 class="card-title">Нет сообщений</h2>
            {% endif %}
            <a class="btn btn-info btn-sm mb-10" href="{% url 'mailings:message_create' %}">Создать новое сообщение</a>
        </div>
{% endblock content %}

mailings/templates/mailings/notification_confirm_delete.html
{% extends './base.html'%}
{% load static %}
{% block content %}
    <div class="container">
      <form method="post">
        {% csrf_token %}
        <p>Удалить рассылку: {{ object.name }}?</p>
        <button type="submit" class="btn btn-danger">Подтвердить удаление</button>
        <a class="btn btn-warning" href="{% url 'mailings:clients' %}">Отменить удаление</a>
      </form>
    </div>
{% endblock %}

mailings/templates/mailings/notification_detail.html
{% extends './base.html'%}
{% load static %}
{% block content %}
  <div class="container px-4 px-lg-5">
            {% if object %}
                <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">{{ object.message.title }}</h2>
                            <p class="card-text">{{ object.status }}</p>
                            <p class="card-text">{{ object.start_at }}</p>
                            <p class="card-text">{{ object.finish_at }}</p>
                            <p class="card-text">{{ object.first_send_time }}</p>
                            <p class="card-text">{{ object.last_send_time}}</p>
                            <p class="card-text">{{ object.text }}</p>
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-danger btn-sm" href="{% url 'mailings:notification_delete' object.pk %}">Удалить</a>
                            {% if notification.status != 'f' %}
                                <a class="btn btn-danger btn-sm mr-10" href="{% url 'mailings:notification_finish' notification.pk %}">Завершить рассылку</a>
                            {% endif %}
                            <a class="btn btn-info btn-sm mb-10" href="{% url 'mailings:notification_update' object.pk %}">Создать новую рассылку</a>
                        </div>

                    </div>
                </div>
            </div>
            {% else %}
                <h2 class="card-title">Нет такой рассылки</h2>
            {% endif %}
        </div>
{% endblock content %}

mailings/templates/mailings/notification_form.html
{% extends './base.html'%}
{% load static %}
{% block content %}
    <div class="container px-4">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {% if object %}
                <button class="btn btn-success" type="submit">Изменить</button>
                <a href="{% url 'mailings:notification_detail'  object.pk %}" class="btn btn-warning" type="submit">Отменить изменения</a>
            {% else %}
              <button class="btn btn-success" type="submit">Добавить</button>
            {% endif %}
          </form>
    </div>
{% endblock content %}

mailings/templates/mailings/notification_list.html
{% extends './base.html'%}
{% load static %}
{% load custom_filters %}
{% block content %}
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Дата Начала</th>
            <th scope="col">Дата Окончания</th>
            <th scope="col">Дата Первой рассылки</th>
            <th scope="col">Дата Последней рассылки</th>
            <th scope="col">Период</th>
            <th scope="col">Статус</th>
            <th scope="col">Действия</th>
          </tr>
        </thead>
        <tbody>
            {% if object_list %}
              {% for notification in object_list %}
                <tr>
                  <th scope="row">{{ notification.pk }}</th>
                  <td>{{ notification.start_at|date:'Y-m-d' }}</td>
                  <td>{{ notification.finish_at|date:'Y-m-d' }}</td>
                  <td>{{ notification.first_send_time|date:'Y-m-d' }}</td>
                  <td>{{ notification.last_send_time|date:'Y-m-d' }}</td>
                  <td>{{ period|get_item:notification.period }}</td>
                  <td>{{ status|get_item:notification.status }}</td>
                  <td>
                    {% if perms.mailings.view_notification %}
                      <a class="btn btn-success btn-sm mr-10" href="{% url 'mailings:notification_detail' notification.pk %}">Просмотреть</a>
                    {% endif %}
                    <a class="btn btn-success btn-sm mr-10" href="{% url 'mailings:notification_detail' notification.pk %}">Просмотреть</a>
                    {% if notification.status != 'f' and perms.mailings.update_status %}
                        <a class="btn btn-danger btn-sm mr-10" href="{% url 'mailings:notification_finish' notification.pk %}">Завершить рассылку</a>
                    {% endif %}
                    {% if perms.mailings.update_notification%}
                        <a class="btn btn-warning  btn-sm mr-10" href="{% url 'mailings:notification_update' notification.pk %}">Изменить</a>
                    {% endif %}
                     {% if perms.mailings.delete_notification %}
                        <a class="btn btn-danger btn-sm mr-10" href="{% url 'mailings:notification_delete' notification.pk %}">Удалить</a>
                     {% endif %}
                  </td>
                </tr>
              {% endfor %}
            {% else %}
                <h2 class="card-title">Нет клиентов</h2>
            {% endif %}
        </tbody>
    </table>
    <a class="btn btn-info btn-sm mb-10 mt-10" href="{% url 'mailings:notification_create' %}">Добавить Рассылку</a>
{% endblock content %}

mailings/templates/mailings/notificationattempt_list.html
{% extends './base.html'%}
{% load static %}
{% load custom_filters %}
{% block content %}
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Время последней попытки</th>
            <th scope="col">Рассылка</th>
            <th scope="col">Статус отправки</th>
            <th scope="col">Сообщение сервера</th>
          </tr>
        </thead>
        <tbody>
            {% if object_list %}
              {% for attempt in object_list %}
                <tr>
                  <th scope="row">{{ attempt.pk }}</th>
                  <td>{{ attempt.last_attempt_at|date:'Y-m-d' }}</td>
                  <td>{{ attempt.notification }}</td>
                  {% if attempt.is_sent %}
                        <td>Отправлено Успешно</td>
                  {% else %}
                    <td>Не отправлено</td>
                  {% endif %}
                  <td>{{ attempt.server_message }}</td>
                </tr>
              {% endfor %}
            {% else %}
                <h2 class="card-title">Нет попыток</h2>
            {% endif %}
        </tbody>
    </table>
{% endblock content %}