blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostDeleteView, PostUpdateView

from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('/posts', PostListView.as_view(), name='posts'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('create', PostCreateView.as_view(), name='post_create'),
    path('update/<int:pk>', PostUpdateView.as_view(), name='post_update'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls',namespace='mailings')),
    path('', include('users.urls',namespace='users')),
    path('', include('blog.urls',namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
NULLABLE = {'blank': True, 'null': True}


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name='заголовок')
    slug = models.CharField(max_length=500, **NULLABLE, verbose_name='slug')
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='img/', **NULLABLE, verbose_name='превью')
    created_at = models.DateTimeField(auto_now_add=True , verbose_name='время создания')
    is_published = models.BooleanField(default=True)
    views_count = models.IntegerField(default=0)


    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'

    def __str__(self):
        return self.title

blog/views.py
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify

from .models import Post
from django.views.generic import DetailView, CreateView, ListView, UpdateView, DeleteView
from blog.services import get_cached_posts


# Create your views here.
class PostCreateView(CreateView):
    model = Post
    fields = ('title', 'content', 'preview',)
    success_url = reverse_lazy('blog:posts')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)


class PostListView(ListView):
    model = Post

    def get_queryset(self, *args, **kwargs):
        queryset = get_cached_posts().filter(is_published=True)
        return queryset

class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

class PostUpdateView(UpdateView):
    model = Post
    fields = ('title', 'content', 'preview',)

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:post_detail', args=[self.kwargs.get('pk')])



class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:posts')

blog/templates/blog/post_confirm_delete.html
{% extends '../mailings/base.html' %}
{% block content %}
    <div class="container">
      <form method="post">
        {% csrf_token %}
        <p>Удалить пост: {{ object.title }}?</p>
        <button type="submit" class="btn btn-danger">Подтвердить удаление</button>
        <a class="btn btn-warning" href="{% url 'blog:posts' %}">Отменить удаление</a>
      </form>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends '../mailings/base.html' %}
{% block content %}
{% if object %}
    <div class="container">
      <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="../../media/{{ object.preview }}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{ object.title }}</h5>
              <p class="card-text">{{ object.content }}</p>
              <p class="card-text"> Просмотров - {{ object.views_count }}</p>
              <a class="btn btn-primary" href="{% url 'blog:post_update' object.pk %}">Изменить</a>
            </div>
          </div>
        </div>
      </div>
    </div>
{% else %}
    <p>Нет</p>
{% endif %}

{% endblock%}

blog/templates/blog/post_form.html
{% extends '../mailings/base.html' %}
{% block content %}
    <div class="container">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% if object %}
            <button class="btn btn-success" type="submit">Изменить</button>
            <a href="{% url 'blog:post_detail'  object.pk %}" class="btn btn-warning" type="submit">Отменить изменения</a>
        {% else %}
          <button class="btn btn-success" type="submit">Добавить</button>
        {% endif %}
      </form>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends '../mailings/base.html' %}
{% block content %}
{% if object_list %}
    <div class="container">
        {% for post in object_list %}
              <div class="card mb-5">
                  <div class="col-md-4 mb-5">
                    <img src="../media/{{ post.preview }}" class="card-img-top"  alt="...">
                  </div>
                  <div class="card-body">
                    <h5 class="card-title">{{ post.title }} </h5>
                    <p class="card-text">{{ post.content }}</p>
                    <a href="{% url 'blog:post_detail' post.pk %}" class="btn btn-primary">Просмотреть пост</a>
                    <a href="{% url 'blog:post_delete' post.pk %}" class="btn btn-danger">Удалить пост</a>
                  </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <p>Нет постов</p>
{% endif %}
<a class="btn btn-success" href="{% url 'blog:post_create' %}">Добавить новый пост</a>

{% endblock%}