blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostDeleteView, PostUpdateView

from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('/posts', PostListView.as_view(), name='posts'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('create', PostCreateView.as_view(), name='post_create'),
    path('update/<int:pk>', PostUpdateView.as_view(), name='post_update'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls',namespace='mailings')),
    path('', include('users.urls',namespace='users')),
    path('', include('blog.urls',namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, recover_password, UsersListView, block_user, unblock_user

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('recover_password/', recover_password, name='recover_password'),
    path('/', UsersListView.as_view(), name='users'),
    path('/block/<int:pk>', block_user, name='block_user'),
    path('/unblock/<int:pk>', unblock_user, name='block_user'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(verbose_name='автар', **NULLABLE)
    country = models.CharField(max_length=55, verbose_name='страна', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [
            ('view_clients_list', 'Может просматривать список пользователей сервиса'),
            ('update_is_blocked', 'Может блокировать пользователей сервиса'),
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget  = forms.HiddenInput()

class EmailForm(forms.Form):
    email = forms.EmailField()

users/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView

from config import settings
from users.forms import UserRegisterForm, UserProfileForm, EmailForm
from users.models import User

class UsersListView(LoginRequiredMixin, ListView):
    model = User

# Create your views here.
class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user_form = form.save(commit=False)
        try:
            send_mail(subject='Подтверждение почты',
                      message='Приветственное сообщение',
                      from_email=settings.EMAIL_HOST_USER,
                      recipient_list=[user_form.email],)
            return super().form_valid(form)
        except:
            return HttpResponseBadRequest("Некорректные данные")

class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

def recover_password(request):
    if request.method == "POST":
        form = EmailForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = get_object_or_404(User, email=email)
            password = ''.join(random.choices(['1', 'd', 'F', '9', '7', 'R', 'c', '2', 'i', 'O', '0'], k=6))
            user.set_password(password)
            user.save()
            send_mail(subject='Новый пароль',
                      message=f'Новый пароль - {password}',
                      from_email=settings.EMAIL_HOST_USER,
                      recipient_list=[email], )
            return HttpResponseRedirect('/')
    else:
        form = EmailForm()
    return render(request, "users/recover_password.html", {"form": form})


def block_user(request, pk):
    user = User.objects.filter(pk=pk).first()
    user.is_active = True
    user.save()
    return HttpResponseRedirect("/")

def unblock_user(request, pk):
    user = User.objects.filter(pk=pk).first()
    user.is_active = False
    user.save()
    return HttpResponseRedirect("/")

users/templates/users/login.html
{% extends 'mailings/base.html' %}
{% block content %}
    <div class="container">
        <div class="row col-12">
            <div class="card">
                <div class="card-title">Вход в систему</div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-outline-success" type="submit">Войти</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

users/templates/users/recover_password.html
{% extends 'mailings/base.html' %}
{% block content %}
    <div class="container">
        <div class="row col-12">
            <div class="card">
                <div class="card-title">Восстановление пароля</div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input class="form-control" name="email">
                        <button class="btn btn-outline-success" type="submit">Сбросить пароль</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

users/templates/users/register.html
{% extends 'mailings/base.html' %}
{% block content %}
    <div class="container">
        <div class="row col-12">
            <div class="card">
                <div class="card-title">Регистрация</div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-outline-success" type="submit">Регистрация</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

users/templates/users/user_form.html
{% extends 'mailings/base.html' %}
{% block content %}
    <div class="container">
        <div class="row col-12">
            <div class="card">
                <div class="card-title">Профайл</div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-outline-success" type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

users/templates/users/user_list.html
{% extends 'mailings/base.html'%}
{% load static %}
{% load custom_filters %}
{% block content %}
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Имя</th>
            <th scope="col">Почта</th>
            <th scope="col">Телефон</th>
            <th scope="col">Заблокирован</th>
          </tr>
        </thead>
        <tbody>
            {% if object_list %}
              {% for user in object_list %}
                <tr>
                  <th scope="row">{{ user.pk }}</th>
                  <td>{{ user.name }}</td>
                  <td>{{ user.email }}</td>
                  <td>{{ user.phone }}</td>
                    {% if perms.users.update_is_blocked %}
                        {% if user.is_blocked %}
                            <td>Заблокирован</td>
                        {% else %}
                             <td>Не Заблокирован</td>
                        {% endif %}
                    {% endif %}
                  <td>
                      {% if not user.is_blocked %}
                        <a class="btn btn-warning  btn-sm mr-10" href="{% url 'users:block_user' user.pk %}">Заблокировать</a>
                      {% else %}
                        <a class="btn btn-success  btn-sm mr-10" href="{% url 'users:unblock_user' user.pk %}">Разблокировать</a>
                      {% endif %}
                  </td>
                </tr>
              {% endfor %}
            {% else %}
                <h2 class="card-title">Нет клиентов</h2>
            {% endif %}
        </tbody>
    </table>
{% endblock content %}